### ISSUE TITLE
plugin breaks sls functions

### ISSUE THREAD

**Issue by karlsburg** [serverless/serverless-client-s3#8]
after adding plugin to serverless project, sls and deploy break.

```
$sls --help
/Users/***/Projects/scrap/serverless/sandbox/node_modules/serverless-client-s3/index.js:5
    SError       = require(S.getServerlessPath('Error')),
                             ^

TypeError: S.getServerlessPath is not a function
    at module.exports.S.classes.Plugin._prompt (/Users/***/Projects/scrap/serverless/sandbox/node_modules/serverless-client-s3/index.js:5:30)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:251:25)
    at new Serverless (/usr/local/lib/node_modules/serverless/lib/Serverless.js:82:37)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:11:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by eahefnawy** [comment]
@karlsburg what version of Serverless are you running?

**Comment by karlsburg** [comment]
version 0.3.2

**Comment by eahefnawy** [comment]
You have to update your Serverless installation to v0.5 :) ... This plugin now expects the new features of Serverless :)

**Comment by UCJava** [comment]
Does this work with Serverless Version: 1.12.1 ? Is there serverless.yml file ? when I tried to create one , I am getting the :

  Type Error ---------------------------------------------

     S.getServerlessPath is not a function
