### ISSUE TITLE
Does not work with serverless 1.0 beta

### ISSUE THREAD

**Issue by davedash** [serverless/serverless-client-s3#42]
Hi, so it seems like `npm install serverless` defaults to the beta, which is fine (seemed a lot easier to get going based on the docs).  Unfortunately I could not get things to work when using this plugin.

I ran into this error:

```
> $ serverless                                                                 

  Type Error ---------------------------------------------

     S.getServerlessPath is not a function

     For debugging logs, run again after setting SLS_DEBUG env var.

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.
```

With debugging on I confirmed that this is coming from this plugin.

Is this still the recommended way to serve a static page using serverless, or should I try something else.

**Comment by kevzettler** [comment]
same issue here

```
Kevins-MBP:projects kevzettler$ serverless --version
1.0.0-beta.2
```

```
Kevins-MBP:whatsbertdoing kevzettler$ SLS_DEBUG=1 serverless client deploy

  Type Error ---------------------------------------------

     S.getServerlessPath is not a function

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

TypeError: S.getServerlessPath is not a function
    at new module.exports.S.classes.Plugin._prompt (/Users/kevzettler/projects/whatsbertdoing/node_modules/serverless-client-s3/index.js:5:30)
    at PluginManager.addPlugin (/Users/kevzettler/.nvm/versions/node/v4.2.6/lib/node_modules/serverless/lib/classes/PluginManager.js:150:28)
    at /Users/kevzettler/.nvm/versions/node/v4.2.6/lib/node_modules/serverless/lib/classes/PluginManager.js:186:12
    at Array.forEach (native)
    at PluginManager.loadServicePlugins (/Users/kevzettler/.nvm/versions/node/v4.2.6/lib/node_modules/serverless/lib/classes/PluginManager.js:183:20)
    at PluginManager.loadAllPlugins (/Users/kevzettler/.nvm/versions/node/v4.2.6/lib/node_modules/serverless/lib/classes/PluginManager.js:33:10)
    at /Users/kevzettler/.nvm/versions/node/v4.2.6/lib/node_modules/serverless/lib/Serverless.js:60:28

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.
```

**Comment by kevzettler** [comment]
I've started a port here: https://github.com/serverless/serverless-client-s3/pull/43

It has the previous functionality of creating an S3 bucket and uploading your `/dist` folder

**Comment by paukul** [comment]
I'm still having this issue with sls 1.14.0 and serverless-client-s3 2.0.0. Anything I can do about it?
